### ISSUE TITLE
[ENH] Simplify the bug issue template

### ISSUE THREAD

**Issue by aminalhazwani** [accurat/.github#1]
**Is your feature request related to a problem? Please describe.**
Filing issues is a pain, we should try our best to make this process as smooth as possible hence my suggestion to simplify the bug template.

**Describe the solution you'd like**
If whoever submits the bug is able to underline:

- steps to reproduce,
- actual behavior,
- and desired outcome 

it's not necessary to ask the submitter to give a bug description, additional context, screenshot, etc. (if they want they to do it they can of course do it but asking for all these details upfront when it's maybe not necessary might be a blocker).

We might also try to simplify the browser section, merging desktop and mobile together (and including by consequence other devices too like tablet, watches, TVs, ...), something like:

- Device: (e.g. Nexus 5, Asus Zenbook)
- OS: (e.g. iOS 8.1, Windows 10)
- Browser: (e.g. Firefox, Safari, Chrome)
- Browser version: (e.g. 66)

What do you all think about it?

**Comment by aminalhazwani** [comment]
In summary, what I'm trying to say it's that we could start with a simpler/smaller/shorter template and iterate on top of that, if we notice that most of the times we don't get all the information we need to make the issue actionable we will then increase the number of upfront requested info.

**Comment by lucafalasco** [comment]
Closed in commit 4ba9182ea22881511f21fd9326630a49bd416a16
